### ISSUE TITLE
Selector Service

### ISSUE THREAD

**Issue by MikeSquall** [capsulajs/selector-service#6]
## General description
The `Selector` service is a custom service which allow to deal with stream of data and to select a specific set of data

#### Prerequisites
None

#### Design description

The `Selector` will exposes 4 methods
```typescript
interface SelectorInterface<Item extends Key, Key> {
  setItems(setItemsRequest: SetItemsRequest<Item>): Promise<void>;
  items$(itemsRequest: ItemsRequest): Observable<Item[]>;
  selectItem(selectItemRequest: SelectItemRequest<Key>): Promise<Item>;
  selectedItem$(selectedItemRequest: SelectedItemRequest): Observable<Item>;
}

interface SetItemsRequest<Item> {
  items: Item[];
}

interface ItemsRequest {}

interface SelectItemRequest<Key> {
  key: Key;
}

interface SelectedItemRequest {}
```
| method               | purpose                                                       |
|-----------------------|----------------------------------------------------------|
|`setItems`            | allows to load items in the `Selector`           |
|`items$`               | allows to access the loaded items               |
|`selectItem`         | allows to select an item                                |
|`selectedItem$`   | allows to access the selected item               |

- [ ] Is it backward compatible ?
- [x] Adds new API
- [ ] Changes existing API
- [ ] Removes existing API

#### Consideration

```gherkin
Given An instance of Selector service
When I input items on it
Then I expect to be able to get those items as an output

Given An instance of Selector service
When I select an item
Then I expect to have this item as selected
```

## Test cases

https://github.com/capsulajs/selector-service/pull/1

## Ready for implementation
- [x] External dependencies have been resolved
- [x] API has been approved
- [x] Test cases have been prepared
- [x] Discussed with Technical lead

## Definition of Done
- [x] Maintainer review
- [x] All tests are implemented 
- [x] Manual QA
- [x] Documentation
- [x] Release notes
- [x] KPI has been reached

## RoadMap

In case there is more than one mergeable point you can specify it here.

NOTICE that DoD is one unit, you CAN'T do implementation then notes then documentation etc.

**Comment by stephanebenayoun** [comment]
@MikeSquall please check if it meets DoD and if yes close this issue
